### PR TITLE
Added static helpers for span based arguments.

### PR DESCRIPTION
**Pull request by azhmur**
I have added Span version of static helper methods with string support.

### CODE REVIEW

**Comment by cocowalla** [comment]
Thanks for the PR!

You know, it always annoys me when libraries don't provide `Span`-based APIs, forcing me to cast to a byte array, so I'm not sure why I didn't do this sooner :grin:

I'll try to take a closer look within the next few days and get this merged and packaged :thumbsup:

**Comment by cocowalla** [comment]
@azhmur hi, sorry it's taken me so long to get round to reviewing this!

.NET Core [added Span-based overloads](https://github.com/dotnet/corefx/commit/154c2a35d5480d359729959f3e3e7d8578a18612) to `HashAlgorithm` a while back, and I was wondering what you thought about making some changes to implement the Span-based `TryComputeHash`, `HashCore` and `TryHashFinal` methods, then restructuring your static helpers if needed?

Some test coverage of the Span-based overloads would also be great if you get a chance, but I don't mind adding it if not 👍

**Comment by azhmur** [comment]
I made some improvements, but supporting both old and new HashAlgorithm features seems not very convinient. OOP works really bad in such cases. I have to change HashSize override to use of protected member, and other inherited members (like HashValue and State) also should be used. Like for example right now after WyHash64.HashCore called HashAlgorithm.Hash/HashValue are empty. I don't think it should be supported.

**Comment by cocowalla** [comment]
@azhmur thanks for this, I've merged it and published a [new NuGet package](https://www.nuget.org/packages/WyHash/1.0.4)!

**Pull request merged**
